### ISSUE TITLE
Captions with HLS videos

### ISSUE THREAD

**Issue by mskorsur** [luwes/videojs-video-element#56]
Hi,

I'm trying to setup captions to work with my videos using videojs-video-element and media-chrome UI. The videos in question use HLS tech (.m3u8), and captions are not added as separate track elements, but are embedded in the video stream itself. Is it possible to setup captions to work in this scenario or is that yet to be supported? When using video.js standalone, without media-chrome, I don't have any issues.

Thanks!

**Comment by luwes** [comment]
I released a fix for m3u8 captions, demo here in the bottom video https://videojs-video-element.vercel.app/
let me know if this works. thanks for the report!
