### ISSUE TITLE
Not working correctly with media-chrome v0.21

### ISSUE THREAD

**Issue by rrisland** [luwes/videojs-video-element#58]
#57 ~~Upgrading the video-js version (8.3.0 -> 8.4.0) solved the problem.~~
I have had the same problem between media-chrome v0.21.0 to v0.21.1, but the upgrade did not solve the problem.

The specific problem is that "when used within media-chrome, operations other than seek are not possible without the controls attribute."

I am new to Github so sorry if I am rude.

**Comment by rrisland** [comment]
Sorry, I changed the title as it seems I was mistaken.
I checked in detail and it works fine with media-chrome v1.0 and also with the current video-js v8.3.0.
It seems that the problem is reproducible only with media-chrome v0.21.

**Comment by luwes** [comment]
Thanks for the feedback, there was indeed a bug in Media Chrome v0.21.
Please use v1. It's fixed there

**Comment by rrisland** [comment]
Thank you, I will use v1.

I am extending this project to create a new VideoElement.
You have helped me a lot. Thanks again.
